/*01_DATA_PREPARATION.SQL
PURPOSE: Create the table schema for the Autism Survey dataset.*/

"""1. Create the table structure"""
CREATE TABLE IF NOT EXISTS autism_survey (
gender VARCHAR(50),
birth_weight VARCHAR(50),
birth_order VARCHAR(50),
premature_birth VARCHAR(10),
birth_asphyxia VARCHAR(10),
breastfeeding VARCHAR(50),
fathers_age VARCHAR(50),
mothers_age VARCHAR(50),
socio_economic VARCHAR(50),
fathers_education VARCHAR(100),
mothers_education VARCHAR(100),
fathers_occupation VARCHAR(100),
mothers_occupation VARCHAR(100),
family_type VARCHAR(50),
family_history VARCHAR(100),
father_illness VARCHAR(100),
consanguinity VARCHAR(100),
threatened_bortion VARCHAR(10),
mothers_illness VARCHAR(100),
drug_use VARCHAR(10),
stress VARCHAR(10),
poor_nutrition VARCHAR(10),
vitamin_d_deficit VARCHAR(10),
mineral_deficiencies VARCHAR(10),
delivery_types VARCHAR(50),
asd NUMERIC
);
"""2. DATA IMPORT STEP"""
-- Note: Data was imported from 'datasav_labeled.csv' (generated by the Python script).
-- If using the pgAdmin Import Tool: Right-click Table > Import/Export > Select File.
-- If using SQL Command:
/*
COPY autism_survey
FROM 'C:\path\to\your\datasav_labeled.csv'
DELIMITER ','
CSV HEADER;
*/
"""3. Initial Data Verification"""
-- This confirms the import was successful and shows the diagnosis split.
SELECT asd, COUNT(*) AS total_count
FROM autism_survey
GROUP BY asd;